name: CI-Pipeline

on:
  push:
    branches:
      - terraform

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          make create-environment
          source venv/bin/activate
          make requirements

      - name: Run Tests and Checks
        run: |
          make run-checks

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: run-tests
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Lambda Layer Packaging
        run: |
          # Ensure dependencies are installed in the folder for the Lambda layer
          rm -rf extract_layer/python
          mkdir -p extract_layer/python
          pip install -r extract_layer_requirements.txt -t extract_layer/python/
          
          # Package the Lambda layer
          cd extract_layer && zip -r ../extract_layer.zip ./*

      - name: Upload Lambda Layer to S3
        run: |
          # Upload the packaged Lambda layer zip file to S3
          aws s3 cp extract_layer.zip s3://your-s3-bucket/extract_layer.zip

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve


