name: CI-Pipeline
on:
  push:
    branches:
      - terraform
jobs:
  run-tests:
    #if: false # this will cause the job to be skipped - delete to enable
    name: run-tests
    runs-on: ubuntu-latest
    # implement me
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          make create-environment
          source venv/bin/activate
          make requirements
      - name: Run Tests and Checks
        run: |
          make run-checks
  deploy-lambda:
    #if: false # this will cause the job to be skipped - delete to enable
    name: deploy-lambda
    # implement me
    runs-on: ubuntu-latest
    needs: run-tests
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentirals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

