name: CI pipeline
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    #if: false # this will cause the job to be skipped - delete to enable
    name: run-tests
    runs-on: ubuntu-latest
    # implement me
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'